- id: "add-license-headers"
  name: "Add License Headers"
  entry: add-license-headers
  description: "Add missing license headers to files by using reuse lint and annotate"
  language: python
  files: '(src|examples|tests)/.*\.(py)|\.(proto)'
  require_serial: true
- id: "tech-review"
  name: "Ansys Technical Review"
  description: "Perform initial technical review on a repository"
  entry: tech-review
  language: python
  pass_filenames: false
- id: "hashed-pre-commit"
  name: "Hashed Pre-Commit Versions"
  description: "Enforce hash-based versions in .pre-commit-config.yaml files"
  entry: hashed-pre-commit
  language: python
  files: '(\.pre-commit-config\.yaml)'