- id: "add-license-headers"
  name: "Add License Headers"
  entry: add-license-headers
  description: "Add missing license headers to files by using reuse lint and annotate"
  language: python
  files: '(src|examples|tests)/.*\.(py)|\.(proto)'
  require_serial: true
- id: "tech-review"
  name: "Ansys Technical Review"
  description: "Perform initial technical review on a repository"
  entry: tech-review
  language: python
  pass_filenames: false